export function renderWebview(nonce: string): string {
  return `<!doctype html>
<html><head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'nonce-${nonce}'">
<style>
:root{--space-1:8px;--space-2:12px;--space-3:16px;--codex-accent:#7a9dff;--codex-on-accent:#111318;--claude-accent:#d97757;--claude-on-accent:#111318}body.vscode-light{--codex-accent:#3941ff;--codex-on-accent:#fff;--claude-accent:#c15f3c;--claude-on-accent:#fff}*{box-sizing:border-box}html,body{height:100%}body{margin:0;overflow:hidden;color:var(--vscode-foreground);background:var(--vscode-sideBar-background);font:var(--vscode-font-size) var(--vscode-font-family)}button,textarea{font:inherit}.shell{height:100%;display:grid;grid-template-rows:auto auto 1fr auto}
header{display:flex;align-items:center;justify-content:flex-end;padding:var(--space-2) var(--space-3)}.header-actions{display:flex;align-items:center;gap:var(--space-1)}.icon{width:38px;height:38px;padding:0;border:0;border-radius:8px;display:grid;place-items:center;background:transparent;color:var(--vscode-descriptionForeground);cursor:pointer}.icon svg,.send svg{width:22px;height:22px;fill:none;stroke:currentColor;stroke-width:2;stroke-linecap:round;stroke-linejoin:round}.icon:hover{background:var(--vscode-toolbar-hoverBackground);color:var(--vscode-foreground)}
#chat{min-height:0;overflow:auto;padding:var(--space-3) var(--space-3) 32px}.message{max-width:780px;margin:0 auto 24px}.user{text-align:right}.user .body{display:inline-block;max-width:92%;padding:10px 13px;border-radius:13px;text-align:left;white-space:pre-wrap;word-break:break-word;background:var(--vscode-input-background);font-size:13px;line-height:1.5}
.tabs{display:flex;align-items:center;gap:4px;min-width:0;padding:0 var(--space-2) var(--space-1);overflow-x:auto;border-bottom:1px solid var(--vscode-widget-border)}.tab{display:flex;align-items:center;max-width:180px;min-width:64px;border:1px solid transparent;border-radius:7px;overflow:hidden;color:var(--vscode-descriptionForeground);background:transparent;font-size:12px}.tab:hover{background:var(--vscode-toolbar-hoverBackground);color:var(--vscode-foreground)}.tab.active{border-color:var(--vscode-widget-border);color:var(--vscode-foreground);background:var(--vscode-input-background)}.tab-select{min-width:0;flex:1;padding:6px 4px 6px 10px;border:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;text-align:left;cursor:pointer;color:inherit;background:transparent}.tab-close{width:26px;height:26px;flex:0 0 auto;padding:0;border:0;display:grid;place-items:center;cursor:pointer;color:inherit;background:transparent;opacity:.7}.tab-close:hover{opacity:1}.tab-close svg{width:14px;height:14px;fill:none;stroke:currentColor;stroke-width:2;stroke-linecap:round}.tab-select:disabled,.tab-close:disabled{opacity:.55;cursor:default}.tab-add{min-width:30px;width:30px;padding:5px;border:1px solid transparent;cursor:pointer;font-size:18px;line-height:1}.chat-page[hidden]{display:none}
.history-view{min-height:0;overflow:auto;padding:var(--space-3)}.history-view[hidden]{display:none}.history-heading{display:flex;align-items:center;justify-content:space-between;margin-bottom:var(--space-2)}.history-heading h2{margin:0;font-size:14px}.history-list{display:grid;gap:var(--space-1)}.history-item{width:100%;padding:10px 12px;border:1px solid var(--vscode-widget-border);border-radius:8px;text-align:left;cursor:pointer;color:var(--vscode-foreground);background:var(--vscode-editorWidget-background,var(--vscode-input-background))}.history-item:hover,.history-item:focus{border-color:var(--vscode-focusBorder);outline:none}.history-title{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-weight:600}.history-meta{display:block;margin-top:4px;color:var(--vscode-descriptionForeground);font-size:11px}.history-empty{padding:20px 0;color:var(--vscode-descriptionForeground)}
.assistant{display:grid;gap:var(--space-2)}.activity{border-left:2px solid var(--vscode-widget-border);padding-left:var(--space-2);color:var(--vscode-descriptionForeground)}.assistant.codex .activity{border-color:var(--codex-accent)}.assistant.claude .activity{border-color:var(--claude-accent)}.activity summary{cursor:pointer;user-select:none;font-size:13px;color:var(--vscode-descriptionForeground)}.assistant.codex .activity summary,.assistant.codex .card-title{color:var(--codex-accent)}.assistant.claude .activity summary,.assistant.claude .card-title{color:var(--claude-accent)}.activity summary:hover{color:var(--vscode-foreground)}.activity-log{max-height:330px;overflow:auto;margin:var(--space-2) 0 0;padding:var(--space-2);border-radius:8px;background:var(--vscode-textCodeBlock-background);white-space:pre-wrap;word-break:break-word;font:12px/1.55 var(--vscode-editor-font-family,monospace);color:var(--vscode-descriptionForeground)}
.card{padding:var(--space-2) 14px;border:1px solid var(--vscode-widget-border);border-radius:10px;background:var(--vscode-editorWidget-background,var(--vscode-input-background))}.card-title{margin-bottom:var(--space-1);font-size:12px;font-weight:700;text-transform:uppercase;letter-spacing:.04em;color:var(--vscode-descriptionForeground)}.card pre{margin:0;white-space:pre-wrap;word-break:break-word;font:13px/1.55 var(--vscode-font-family)}.interaction,.failure{border-color:var(--vscode-widget-border)}.permission{border-width:2px;box-shadow:0 5px 18px rgba(0,0,0,.14)}.assistant.codex .permission{border-color:var(--codex-accent)}.assistant.claude .permission{border-color:var(--claude-accent)}.card-actions{display:flex;flex-wrap:wrap;gap:var(--space-1);margin-top:var(--space-2)}.card-action{min-height:34px;padding:6px 14px;border:1px solid var(--vscode-button-border,transparent);border-radius:6px;cursor:pointer;color:var(--vscode-button-secondaryForeground);background:var(--vscode-button-secondaryBackground)}.card-action:hover{background:var(--vscode-button-secondaryHoverBackground)}.assistant.codex .card-action.primary{border-color:var(--codex-accent);color:var(--codex-on-accent);background:var(--codex-accent)}.assistant.claude .card-action.primary{border-color:var(--claude-accent);color:var(--claude-on-accent);background:var(--claude-accent)}.card-action:disabled{opacity:.55;cursor:default}
footer{padding:0 var(--space-2) var(--space-2);background:linear-gradient(transparent,var(--vscode-sideBar-background) 18px)}.composer{max-width:780px;margin:0 auto;padding:var(--space-2);border:1px solid var(--vscode-input-border,var(--vscode-widget-border));border-radius:14px;background:var(--vscode-input-background);box-shadow:0 5px 18px rgba(0,0,0,.12)}.composer:focus-within{border-color:var(--vscode-focusBorder)}#attachments{display:none;margin:0 4px var(--space-1);color:var(--vscode-descriptionForeground);font-size:12px}textarea{display:block;width:100%;min-height:58px;max-height:160px;padding:4px 5px var(--space-1);resize:none;border:0;outline:0;color:var(--vscode-input-foreground);background:transparent;font-size:13px;line-height:1.5}.composer-row{display:flex;align-items:center;gap:var(--space-1)}.route{margin-left:auto;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--vscode-descriptionForeground);font-size:12px}.route strong{color:var(--vscode-foreground);font-weight:600}.route.codex strong{color:var(--codex-accent)}.route.claude strong{color:var(--claude-accent)}.send{width:38px;height:38px;flex:0 0 auto;padding:0;border:0;border-radius:50%;display:grid;place-items:center;cursor:pointer;color:var(--vscode-button-foreground);background:var(--vscode-button-background)}.send:hover{background:var(--vscode-button-hoverBackground)}.send:disabled{opacity:.4;cursor:default}.ansi-bold{font-weight:700}.ansi-dim{opacity:.68}
.phases{display:flex;flex-wrap:wrap;gap:6px}.phase{display:inline-flex;align-items:center;gap:5px;padding:5px 8px;border:1px solid var(--vscode-widget-border);border-radius:999px;color:var(--vscode-descriptionForeground);font-size:11px}.phase::before{content:'';width:6px;height:6px;border-radius:50%;background:var(--vscode-descriptionForeground)}.phase.running{border-color:var(--vscode-progressBar-background);color:var(--vscode-foreground)}.phase.running::before{background:var(--vscode-progressBar-background)}.phase.completed::before{background:var(--vscode-testing-iconPassed)}.phase.failed::before{background:var(--vscode-testing-iconFailed)}.phase .model{opacity:.72}
</style></head><body><div class="shell">
<header><div class="header-actions"><button class="icon" data-action="history" title="Previous chats" aria-label="Previous chats"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 6h13M8 12h13M8 18h13M3 6h.01M3 12h.01M3 18h.01"/></svg></button><button class="icon" data-action="settings" title="Settings" aria-label="Settings"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.1 2.1-.06-.06a1.7 1.7 0 0 0-1.88-.34 1.7 1.7 0 0 0-1.04 1.56v.1h-3v-.1a1.7 1.7 0 0 0-1.04-1.56 1.7 1.7 0 0 0-1.88.34l-.06.06-2.1-2.1.06-.06A1.7 1.7 0 0 0 7.04 15 1.7 1.7 0 0 0 5.5 14H5.4v-3h.1A1.7 1.7 0 0 0 7.04 10a1.7 1.7 0 0 0-.34-1.88l-.06-.06 2.1-2.1.06.06a1.7 1.7 0 0 0 1.88.34A1.7 1.7 0 0 0 11.72 4.8v-.1h3v.1a1.7 1.7 0 0 0 1.04 1.56 1.7 1.7 0 0 0 1.88-.34l.06-.06 2.1 2.1-.06.06A1.7 1.7 0 0 0 19.4 10c.18.66.78 1.12 1.46 1.12h.1v3h-.1c-.68 0-1.28.46-1.46 1.12Z"/></svg></button></div></header>
<nav id="tabs" class="tabs" aria-label="Open chats"></nav>
<section id="history-view" class="history-view" hidden><div class="history-heading"><h2>Previous chats</h2><button id="history-close" class="icon" title="Back to chat" aria-label="Back to chat"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m15 18-6-6 6-6"/></svg></button></div><div id="history-list" class="history-list"></div></section>
<main id="chat" aria-live="polite"></main>
<footer><div class="composer"><div id="attachments"></div><textarea id="prompt" rows="2" placeholder="Ask AIRO anything…"></textarea><div class="composer-row"><button class="icon" id="attach" title="Attach files" aria-label="Attach files"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m21.4 11.6-8.8 8.8a6 6 0 0 1-8.5-8.5l9.5-9.5a4 4 0 0 1 5.7 5.7l-9.5 9.5a2 2 0 0 1-2.8-2.8l8.8-8.8"/></svg></button><div class="route" id="route"><strong>Auto</strong> · Routing · auto</div><button class="send" id="send" title="Send" aria-label="Send"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m5 12 14-7-7 14-2-5-5-2Z"/></svg></button></div></div></footer>
</div><script nonce="${nonce}">
const vscode=acquireVsCodeApi(),chat=document.getElementById('chat'),tabBar=document.getElementById('tabs'),historyView=document.getElementById('history-view'),historyList=document.getElementById('history-list'),footer=document.querySelector('footer'),prompt=document.getElementById('prompt'),attachments=document.getElementById('attachments'),route=document.getElementById('route'),sendButton=document.getElementById('send'),tabStates=new Map();let tabItems=[],activeChatId,active,running=false,stopping=false,awaitingInput=false,provider='auto';
const sendIcon='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m5 12 14-7-7 14-2-5-5-2Z"/></svg>',stopIcon='<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="7" y="7" width="10" height="10" rx="1"/></svg>';
const scroll=()=>requestAnimationFrame(()=>{chat.scrollTop=chat.scrollHeight;document.querySelectorAll('.activity-log').forEach(log=>log.scrollTop=log.scrollHeight)});
const ensureTab=(id,title='New chat')=>{if(tabStates.has(id))return tabStates.get(id);const page=document.createElement('div'),state={id,title,page,active:undefined,running:false,stopping:false,awaitingInput:false,provider:'auto',draft:'',files:[],route:{provider:'Auto',model:'Routing',tier:'auto'}};page.className='chat-page';page.hidden=true;chat.append(page);tabStates.set(id,state);return state};
const current=()=>tabStates.get(activeChatId);
const showRoute=state=>{route.className='route '+state.provider;route.replaceChildren();const strong=document.createElement('strong');strong.textContent=state.route.provider;route.append(strong,' · '+state.route.model+' · '+state.route.tier)};
const showAttachments=state=>{attachments.textContent=state.files.length?'Attached: '+state.files.join(', '):'';attachments.style.display=state.files.length?'block':'none'};
const renderTabs=()=>{tabBar.replaceChildren();tabItems.forEach(item=>{const tab=document.createElement('div'),select=document.createElement('button'),close=document.createElement('button');tab.className='tab'+(item.id===activeChatId?' active':'');select.className='tab-select';select.textContent=item.title;select.title=item.title;select.disabled=running&&item.id!==activeChatId;select.onclick=()=>activateTab(item.id,true);close.className='tab-close';close.innerHTML='<svg viewBox="0 0 16 16" aria-hidden="true"><path d="m4 4 8 8M12 4l-8 8"/></svg>';close.title='Close '+item.title;close.setAttribute('aria-label','Close '+item.title);close.disabled=running&&item.id===activeChatId;close.onclick=()=>vscode.postMessage({type:'closeTab',chatId:item.id});tab.append(select,close);tabBar.append(tab)});const add=document.createElement('button');add.className='tab-add';add.textContent='+';add.title='New chat';add.setAttribute('aria-label','New chat');add.disabled=running;add.onclick=()=>vscode.postMessage({type:'newTab'});tabBar.append(add)};
const closeHistory=()=>{historyView.hidden=true;chat.hidden=false;footer.hidden=false;tabBar.hidden=false};
const activateTab=(id,notify)=>{closeHistory();if(id===activeChatId)return;const prior=current();if(prior){prior.draft=prompt.value;prior.active=active;prior.running=running;prior.stopping=stopping;prior.awaitingInput=awaitingInput;prior.provider=provider;prior.page.hidden=true}const state=ensureTab(id,tabItems.find(item=>item.id===id)?.title);activeChatId=id;state.page.hidden=false;active=state.active;running=state.running;stopping=state.stopping;awaitingInput=state.awaitingInput;provider=state.provider;prompt.value=state.draft;showRoute(state);showAttachments(state);updateSendButton();renderTabs();scroll();if(notify)vscode.postMessage({type:'switchTab',chatId:id})};
const showHistory=sessions=>{historyList.replaceChildren();if(!sessions.length){const empty=document.createElement('div');empty.className='history-empty';empty.textContent='No previous chats in this workspace.';historyList.append(empty)}sessions.forEach(session=>{const button=document.createElement('button'),title=document.createElement('span'),meta=document.createElement('span'),date=new Date(session.updatedAt);button.className='history-item';title.className='history-title';meta.className='history-meta';title.textContent=session.description||'Untitled chat';meta.textContent=(Number.isNaN(date.getTime())?'Unknown date':date.toLocaleString())+' · '+session.turnCount+' '+(session.turnCount===1?'turn':'turns')+(session.open?' · open':'');button.append(title,meta);button.onclick=()=>vscode.postMessage({type:'openSession',sessionId:session.sessionId});historyList.append(button)});historyView.hidden=false;chat.hidden=true;footer.hidden=true;tabBar.hidden=true};
const section=role=>{const node=document.createElement('section');node.className='message '+role;current().page.append(node);return node};
const addUser=text=>{const node=section('user'),body=document.createElement('div');body.className='body';body.textContent=text;node.append(body);scroll()};
const beginRun=()=>{const node=section('assistant '+provider),phases=document.createElement('div'),details=document.createElement('details'),summary=document.createElement('summary'),log=document.createElement('pre');phases.className='phases';phases.setAttribute('aria-label','Workflow progress');details.className='activity';summary.textContent='Working… · show activity';log.className='activity-log';details.append(summary,log);node.append(phases,details);active={node,phases,details,summary,log};current().active=active;scroll()};
const ensureRun=()=>{if(!active)beginRun();return active};
const updatePhase=message=>{const run=ensureRun(),id='phase-'+message.phaseIndex,prior=run.phases.querySelector('#'+id),chip=prior||document.createElement('span');chip.id=id;chip.className='phase '+(message.state==='started'?'running':message.state);chip.replaceChildren();const label=document.createElement('span'),model=document.createElement('span');label.textContent=message.title||message.kind;model.className='model';model.textContent=message.provider?(message.provider+' · '+(message.model||message.tier||'')):'';chip.append(label,model);if(!prior)run.phases.append(chip);run.summary.textContent='Workflow in progress · show activity';scroll()};
const resolveActions=(actions,label)=>{actions.querySelectorAll('button').forEach(item=>item.disabled=true);actions.setAttribute('aria-label',label)};
const addCard=(kind,title,text,action)=>{const run=ensureRun(),card=document.createElement('div'),heading=document.createElement('div'),body=document.createElement('pre');card.className='card '+kind;heading.className='card-title';heading.textContent=title;body.textContent=text;card.append(heading,body);if(action){card.setAttribute('role','alert');const actions=document.createElement('div');actions.className='card-actions';const options=action==='permission'?[['Approve','approve',true],['Decline','decline',false]]:[['Reply','reply',true]];options.forEach(([label,value,primary])=>{const button=document.createElement('button');button.textContent=label;button.className='card-action'+(primary?' primary':'');button.onclick=()=>{if(value==='reply'){const reply=prompt.value.trim();if(!reply){prompt.focus();return}resolveActions(actions,'Reply sent');submitPrompt()}else{resolveActions(actions,label+' selected');vscode.postMessage({type:'prompt',text:value})}};actions.append(button)});card.append(actions);requestAnimationFrame(()=>actions.querySelector('button').focus())}run.node.append(card);scroll()};
const appendAnsi=(target,text)=>{let index=0,match;const pattern=new RegExp(String.fromCharCode(27)+'\\\\[([0-9;]*)m','g'),state=target._ansiState??={bold:false,dim:false};const append=value=>{if(!value)return;const span=document.createElement('span');span.textContent=value;span.className=[state.bold?'ansi-bold':'',state.dim?'ansi-dim':''].filter(Boolean).join(' ');target.append(span)};while((match=pattern.exec(text))){append(text.slice(index,match.index));for(const code of (match[1]||'0').split(';').map(Number)){if(code===0){state.bold=false;state.dim=false}else if(code===1)state.bold=true;else if(code===2)state.dim=true;else if(code===22){state.bold=false;state.dim=false}}index=pattern.lastIndex}append(text.slice(index));target.scrollTop=target.scrollHeight;scroll()};
const updateSendButton=()=>{sendButton.innerHTML=running?stopIcon:sendIcon;sendButton.title=stopping?'Stopping…':running?'Stop execution':'Send';sendButton.setAttribute('aria-label',sendButton.title);sendButton.disabled=stopping;prompt.placeholder=awaitingInput?'Type a reply, then press Enter…':running?'AIRO is working…':'Ask AIRO anything…';renderTabs()};
const submitPrompt=()=>{const text=prompt.value.trim();if(!text)return;addUser(text);prompt.value='';current().draft='';prompt.style.height='auto';vscode.postMessage({type:'prompt',text})};
const send=()=>{if(running){vscode.postMessage({type:'action',action:'stop'});return}submitPrompt()};
sendButton.onclick=send;prompt.addEventListener('input',()=>{current().draft=prompt.value;prompt.style.height='auto';prompt.style.height=Math.min(prompt.scrollHeight,160)+'px'});prompt.addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();if(!running||awaitingInput)submitPrompt()}});document.getElementById('attach').onclick=()=>vscode.postMessage({type:'attach'});document.getElementById('history-close').onclick=closeHistory;document.querySelectorAll('[data-action]').forEach(button=>button.onclick=()=>vscode.postMessage({type:'action',action:button.dataset.action}));
window.addEventListener('message',event=>{const message=event.data,state=current();if(message.type==='tabs'){tabItems=message.tabs;tabItems.forEach(item=>{const tab=ensureTab(item.id,item.title);tab.title=item.title});if(!activeChatId||message.activeChatId!==activeChatId)activateTab(message.activeChatId,false);else renderTabs()}else if(message.type==='history')showHistory(message.sessions);else if(message.type==='replaceTabId'){const tab=tabStates.get(message.oldId);if(tab){tabStates.delete(message.oldId);tab.id=message.newId;tabStates.set(message.newId,tab);if(activeChatId===message.oldId)activeChatId=message.newId}}else if(message.type==='removeTab'){const tab=tabStates.get(message.chatId);if(tab)tab.page.remove();tabStates.delete(message.chatId);if(activeChatId===message.chatId)activeChatId=undefined}else if(message.type==='activateTab')activateTab(message.chatId,false);else if(message.type==='route'){provider=['codex','claude'].includes(message.provider)?message.provider:'auto';state.provider=provider;state.route={provider:message.provider,model:message.model,tier:message.tier};if(active)active.node.className='message assistant '+provider;showRoute(state)}else if(message.type==='phase')updatePhase(message);else if(message.type==='state'){running=message.running;stopping=message.stopping;awaitingInput=message.awaitingInput;Object.assign(state,{running,stopping,awaitingInput});updateSendButton()}else if(message.type==='attachments'){state.files=message.files;showAttachments(state)}else if(message.type==='start')beginRun();else if(message.type==='activity')appendAnsi(ensureRun().log,message.text);else if(message.type==='final')addCard('result','Final result',message.text);else if(message.type==='interaction')addCard('interaction','Input required',message.text,'reply');else if(message.type==='permission')addCard('interaction permission','Permission required',message.text,'permission');else if(message.type==='failure')addCard('failure','Run failed',message.text);else if(message.type==='end'){const run=ensureRun();run.summary.textContent=(message.stopped?'Stopped':message.code===0?'Completed':'Failed')+' · show activity';active=undefined;state.active=undefined;prompt.focus()}else if(message.type==='notice')addCard('failure','Notice',message.value);else if(message.type==='help')addCard('result','Commands','/new, /status, /sessions, /models, /account, /usage [limit], /logs, /doctor, /attach, /feedback good|bad [note], /clear.');else if(message.type==='clear'){state.page.replaceChildren();active=undefined;state.active=undefined}else if(message.type==='focus')prompt.focus();scroll()});vscode.postMessage({type:'ready'});
</script></body></html>`;
}
