export function renderWebview(nonce: string): string {
  return `<!doctype html>
<html><head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'nonce-${nonce}'">
<style>
*{box-sizing:border-box}html,body{height:100%}body{margin:0;overflow:hidden;color:var(--vscode-foreground);background:var(--vscode-sideBar-background);font:var(--vscode-font-size) var(--vscode-font-family)}button,textarea{font:inherit}.shell{height:100%;display:grid;grid-template-rows:auto 1fr auto}
header{display:flex;align-items:center;justify-content:space-between;padding:13px 16px 10px}h1{font-size:13px;line-height:1;margin:0}.session{margin-top:5px;color:var(--vscode-descriptionForeground);font-size:11px}.header-actions{display:flex;gap:3px}.icon{width:28px;height:28px;border:0;border-radius:7px;background:transparent;color:var(--vscode-descriptionForeground);cursor:pointer}.icon:hover{background:var(--vscode-toolbar-hoverBackground);color:var(--vscode-foreground)}
#chat{min-height:0;overflow:auto;padding:16px 16px 34px}.message{max-width:780px;margin:0 auto 22px}.label{margin-bottom:7px;color:var(--vscode-descriptionForeground);font-size:11px;font-weight:600}.user{text-align:right}.user .body{display:inline-block;max-width:92%;padding:9px 12px;border-radius:13px;text-align:left;white-space:pre-wrap;word-break:break-word;background:var(--vscode-input-background)}
.assistant{display:grid;gap:10px}.activity{border-left:2px solid var(--vscode-terminal-ansiCyan);padding-left:10px;color:var(--vscode-descriptionForeground)}.activity summary{cursor:pointer;user-select:none;font-size:12px;color:var(--vscode-terminal-ansiCyan)}.activity summary:hover{color:var(--vscode-foreground)}.activity-log{max-height:330px;overflow:auto;margin:9px 0 0;padding:10px;border-radius:8px;background:var(--vscode-textCodeBlock-background);white-space:pre-wrap;word-break:break-word;font:11px/1.5 var(--vscode-editor-font-family,monospace);color:var(--vscode-descriptionForeground)}
.card{padding:12px 13px;border:1px solid;border-radius:10px}.card-title{margin-bottom:7px;font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:.04em}.card pre{margin:0;white-space:pre-wrap;word-break:break-word;font:inherit;line-height:1.55}.result{border-color:color-mix(in srgb,var(--vscode-terminal-ansiGreen) 55%,transparent);background:color-mix(in srgb,var(--vscode-terminal-ansiGreen) 8%,transparent)}.result .card-title{color:var(--vscode-terminal-ansiGreen)}.interaction{border-color:color-mix(in srgb,var(--vscode-terminal-ansiYellow) 60%,transparent);background:color-mix(in srgb,var(--vscode-terminal-ansiYellow) 9%,transparent)}.interaction .card-title{color:var(--vscode-terminal-ansiYellow)}.failure{border-color:color-mix(in srgb,var(--vscode-terminal-ansiRed) 60%,transparent);background:color-mix(in srgb,var(--vscode-terminal-ansiRed) 9%,transparent)}.failure .card-title{color:var(--vscode-terminal-ansiRed)}
footer{padding:0 12px 12px;background:linear-gradient(transparent,var(--vscode-sideBar-background) 18px)}.composer{max-width:780px;margin:0 auto;padding:10px;border:1px solid var(--vscode-input-border,var(--vscode-widget-border));border-radius:14px;background:var(--vscode-input-background);box-shadow:0 5px 18px rgba(0,0,0,.12)}.composer:focus-within{border-color:var(--vscode-focusBorder)}#attachments{display:none;margin:0 4px 7px;color:var(--vscode-descriptionForeground);font-size:11px}textarea{display:block;width:100%;min-height:54px;max-height:160px;padding:3px 4px 8px;resize:none;border:0;outline:0;color:var(--vscode-input-foreground);background:transparent;line-height:1.45}.composer-row{display:flex;align-items:center;gap:6px}.route{margin-left:auto;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--vscode-descriptionForeground);font-size:11px}.route strong{color:var(--vscode-foreground);font-weight:500}.send{width:30px;height:30px;flex:0 0 auto;border:0;border-radius:50%;display:grid;place-items:center;cursor:pointer;color:var(--vscode-button-foreground);background:var(--vscode-button-background);font-size:17px}.send:disabled{opacity:.4;cursor:default}
.ansi-black{color:var(--vscode-terminal-ansiBlack)}.ansi-red{color:var(--vscode-terminal-ansiRed)}.ansi-green{color:var(--vscode-terminal-ansiGreen)}.ansi-yellow{color:var(--vscode-terminal-ansiYellow)}.ansi-blue{color:var(--vscode-terminal-ansiBlue)}.ansi-magenta{color:var(--vscode-terminal-ansiMagenta)}.ansi-cyan{color:var(--vscode-terminal-ansiCyan)}.ansi-white{color:var(--vscode-terminal-ansiWhite)}.ansi-gray{color:var(--vscode-terminal-ansiBrightBlack)}.ansi-bold{font-weight:700}.ansi-dim{opacity:.68}
</style></head><body><div class="shell">
<header><div><h1>AIRO</h1><div id="session" class="session">Connecting…</div></div><div class="header-actions"><button class="icon" data-action="new" title="New chat">＋</button><button class="icon" data-action="settings" title="Settings">⚙</button></div></header>
<main id="chat"></main>
<footer><div class="composer"><div id="attachments"></div><textarea id="prompt" rows="2" placeholder="Ask AIRO anything…"></textarea><div class="composer-row"><button class="icon" id="attach" title="Attach files">＋</button><div class="route" id="route"><strong>Auto</strong> · Routing · auto</div><button class="send" id="send" title="Send">↑</button></div></div></footer>
</div><script nonce="${nonce}">
const vscode=acquireVsCodeApi(),chat=document.getElementById('chat'),prompt=document.getElementById('prompt'),attachments=document.getElementById('attachments'),route=document.getElementById('route'),sendButton=document.getElementById('send');let active,running=false,awaitingInput=false;
const scroll=()=>requestAnimationFrame(()=>chat.scrollTop=chat.scrollHeight);
const section=role=>{const node=document.createElement('section');node.className='message '+role;chat.append(node);return node};
const addUser=text=>{const node=section('user'),label=document.createElement('div'),body=document.createElement('div');label.className='label';label.textContent='You';body.className='body';body.textContent=text;node.append(label,body);scroll()};
const beginRun=()=>{const node=section('assistant'),details=document.createElement('details'),summary=document.createElement('summary'),log=document.createElement('pre');details.className='activity';summary.textContent='Working… · show activity';log.className='activity-log';details.append(summary,log);node.append(details);active={node,details,summary,log};scroll()};
const ensureRun=()=>{if(!active)beginRun();return active};
const addCard=(kind,title,text,action)=>{const run=ensureRun(),card=document.createElement('div'),heading=document.createElement('div'),body=document.createElement('pre');card.className='card '+kind;heading.className='card-title';heading.textContent=title;body.textContent=text;card.append(heading,body);if(action){const button=document.createElement('button');button.textContent='Approve';button.className='send';button.style.cssText='margin-top:10px;padding:5px 12px;width:auto;height:auto;border-radius:6px';button.onclick=()=>{button.disabled=true;vscode.postMessage({type:'prompt',text:'approve'})};card.append(button)}run.node.append(card);scroll()};
const ansiColors={30:'ansi-black',31:'ansi-red',32:'ansi-green',33:'ansi-yellow',34:'ansi-blue',35:'ansi-magenta',36:'ansi-cyan',37:'ansi-white',90:'ansi-gray'};
const appendAnsi=(target,text)=>{let index=0,match;const pattern=new RegExp(String.fromCharCode(27)+'\\\\[([0-9;]*)m','g'),state=target._ansiState??={color:'',bold:false,dim:false};const append=value=>{if(!value)return;const span=document.createElement('span');span.textContent=value;span.className=[state.color,state.bold?'ansi-bold':'',state.dim?'ansi-dim':''].filter(Boolean).join(' ');target.append(span)};while((match=pattern.exec(text))){append(text.slice(index,match.index));for(const code of (match[1]||'0').split(';').map(Number)){if(code===0){state.color='';state.bold=false;state.dim=false}else if(code===1)state.bold=true;else if(code===2)state.dim=true;else if(code===22){state.bold=false;state.dim=false}else if(code===39)state.color='';else if(ansiColors[code])state.color=ansiColors[code]}index=pattern.lastIndex}append(text.slice(index));scroll()};
const send=()=>{const text=prompt.value.trim();if(!text||sendButton.disabled)return;addUser(text);prompt.value='';prompt.style.height='auto';vscode.postMessage({type:'prompt',text})};
sendButton.onclick=send;prompt.addEventListener('input',()=>{prompt.style.height='auto';prompt.style.height=Math.min(prompt.scrollHeight,160)+'px'});prompt.addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();send()}});document.getElementById('attach').onclick=()=>vscode.postMessage({type:'attach'});document.querySelectorAll('[data-action]').forEach(button=>button.onclick=()=>vscode.postMessage({type:'action',action:button.dataset.action}));
window.addEventListener('message',event=>{const message=event.data;if(message.type==='route'){route.replaceChildren();const strong=document.createElement('strong');strong.textContent=message.provider;route.append(strong,' · '+message.model+' · '+message.tier)}else if(message.type==='session')document.getElementById('session').textContent=message.value;else if(message.type==='state'){running=message.running;awaitingInput=message.awaitingInput;sendButton.disabled=running&&!awaitingInput;prompt.placeholder=awaitingInput?'Reply to continue…':running?'AIRO is working…':'Ask AIRO anything…'}else if(message.type==='attachments'){attachments.textContent=message.files.length?'Attached: '+message.files.join(', '):'';attachments.style.display=message.files.length?'block':'none'}else if(message.type==='start')beginRun();else if(message.type==='activity')appendAnsi(ensureRun().log,message.text);else if(message.type==='final')addCard('result','Final result',message.text);else if(message.type==='interaction')addCard('interaction','Input required',message.text);else if(message.type==='permission')addCard('interaction','Permission required',message.text,true);else if(message.type==='failure')addCard('failure','Run failed',message.text);else if(message.type==='end'){const run=ensureRun();run.summary.textContent=(message.code===0?'Completed':'Failed')+' · show activity';active=undefined;prompt.focus()}else if(message.type==='notice')addCard('failure','Notice',message.value);else if(message.type==='help')addCard('result','Commands','/new [title], /status, /sessions, /models, /account, /usage [limit], /logs, /doctor, /attach, /feedback good|bad [note], /clear.');else if(message.type==='clear'){chat.replaceChildren();active=undefined}else if(message.type==='focus')prompt.focus()});vscode.postMessage({type:'ready'});
</script></body></html>`;
}
